- name: Configure webserver with nginx
  hosts: webservers
  become: True
  tasks:
  - name: Install epel-repo
    shell: wget -O /etc/yum.repos.d/epel.repo http://mirrors.aliyun.com/repo/epel-7.repo

  - name: Install nginx
    yum: name=nginx state=latest

  - name: copy nginx config file
    copy: src=files/nginx.conf dest=/etc/nginx/nginx.conf

  - name: copy index.html
    copy: src=template/index.html.j2 dest=/usr/share/nginx/html/index.html

  - name: start nginx
    service: name=nginx state=restarted
